import type { ReactNode } from "react";

/**
 * A small markdown renderer for the Brief. The Brief is generated by this
 * app from its own database, but it is still rendered as React elements
 * rather than injected HTML — no `dangerouslySetInnerHTML`, and no new
 * dependency for one document.
 *
 * It covers what `lib/services/brief-markdown.ts` emits: an H1 title, H2
 * sections, blockquotes, pipe tables, bullet lists and paragraphs, with
 * bold, italic and inline code inside.
 */
export function Markdown({ source }: { source: string }) {
  return <div className="flex flex-col gap-3">{blocks(source)}</div>;
}

function blocks(source: string): ReactNode[] {
  const lines = source.replace(/\r\n/g, "\n").split("\n");
  const out: ReactNode[] = [];
  let index = 0;
  let key = 0;

  while (index < lines.length) {
    const line = lines[index];

    if (!line.trim()) {
      index++;
      continue;
    }

    if (line.startsWith("### ")) {
      out.push(
        <h3 key={key++} className="font-display text-[15px] font-bold text-ink">
          {inline(line.slice(4))}
        </h3>,
      );
      index++;
      continue;
    }

    if (line.startsWith("## ")) {
      out.push(
        <h2
          key={key++}
          className="mt-3 font-display text-[19px] font-bold tracking-[-0.02em] text-ink"
        >
          {inline(line.slice(3))}
        </h2>,
      );
      index++;
      continue;
    }

    if (line.startsWith("# ")) {
      out.push(
        <h1 key={key++} className="font-display text-[24px] font-bold tracking-[-0.02em] text-ink">
          {inline(line.slice(2))}
        </h1>,
      );
      index++;
      continue;
    }

    if (/^(-{3,}|\*{3,})$/.test(line.trim())) {
      out.push(<hr key={key++} className="border-line" />);
      index++;
      continue;
    }

    if (line.startsWith(">")) {
      const quote: string[] = [];
      while (index < lines.length && lines[index].startsWith(">")) {
        quote.push(lines[index].replace(/^>\s?/, ""));
        index++;
      }
      out.push(
        <blockquote
          key={key++}
          className="border-l-2 border-line pl-3 text-sm italic text-ink-soft"
        >
          {inline(quote.join(" "))}
        </blockquote>,
      );
      continue;
    }

    if (line.trimStart().startsWith("|")) {
      const table: string[] = [];
      while (index < lines.length && lines[index].trimStart().startsWith("|")) {
        table.push(lines[index].trim());
        index++;
      }
      out.push(renderTable(table, key++));
      continue;
    }

    if (/^\s*[-*]\s+/.test(line)) {
      const items: string[] = [];
      while (index < lines.length && /^\s*[-*]\s+/.test(lines[index])) {
        items.push(lines[index].replace(/^\s*[-*]\s+/, ""));
        index++;
      }
      out.push(
        <ul key={key++} className="list-disc pl-5 text-[15px] text-ink">
          {items.map((item, i) => (
            <li key={i}>{inline(item)}</li>
          ))}
        </ul>,
      );
      continue;
    }

    if (/^\s*\d+\.\s+/.test(line)) {
      const items: string[] = [];
      while (index < lines.length && /^\s*\d+\.\s+/.test(lines[index])) {
        items.push(lines[index].replace(/^\s*\d+\.\s+/, ""));
        index++;
      }
      out.push(
        <ol key={key++} className="list-decimal pl-5 text-[15px] text-ink">
          {items.map((item, i) => (
            <li key={i}>{inline(item)}</li>
          ))}
        </ol>,
      );
      continue;
    }

    const paragraph: string[] = [];
    while (
      index < lines.length &&
      lines[index].trim() &&
      !lines[index].startsWith("#") &&
      !lines[index].startsWith(">") &&
      !lines[index].trimStart().startsWith("|") &&
      !/^\s*[-*]\s+/.test(lines[index]) &&
      !/^\s*\d+\.\s+/.test(lines[index])
    ) {
      paragraph.push(lines[index]);
      index++;
    }
    out.push(
      <p key={key++} className="text-[15px] leading-relaxed text-ink">
        {inline(paragraph.join(" "))}
      </p>,
    );
  }

  return out;
}

function renderTable(rows: string[], key: number): ReactNode {
  const cells = rows
    .filter((row) => !/^\|\s*:?-{2,}/.test(row))
    .map((row) =>
      row
        .replace(/^\|/, "")
        .replace(/\|$/, "")
        .split("|")
        .map((cell) => cell.trim()),
    );
  if (cells.length === 0) return null;
  const [header, ...body] = cells;

  return (
    <div key={key} className="overflow-x-auto">
      <table className="w-full min-w-[420px] border-collapse text-left text-[13px]">
        <thead>
          <tr>
            {header.map((cell, i) => (
              <th key={i} className="border-b border-line py-1.5 pr-3 label-tracked">
                {inline(cell)}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {body.map((row, i) => (
            <tr key={i}>
              {row.map((cell, j) => (
                <td key={j} className="border-b border-line py-1.5 pr-3 text-ink tabular-nums">
                  {inline(cell)}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

/** Bold, italic and inline code, rendered as elements rather than HTML. */
function inline(text: string): ReactNode[] {
  const parts: ReactNode[] = [];
  const pattern = /(\*\*[^*]+\*\*|`[^`]+`|_[^_]+_)/g;
  let last = 0;
  let match: RegExpExecArray | null;
  let key = 0;

  while ((match = pattern.exec(text))) {
    if (match.index > last) parts.push(text.slice(last, match.index));
    const token = match[0];
    if (token.startsWith("**")) {
      parts.push(
        <strong key={key++} className="font-semibold">
          {token.slice(2, -2)}
        </strong>,
      );
    } else if (token.startsWith("`")) {
      parts.push(
        <code key={key++} className="rounded bg-sunken px-1 py-0.5 text-[13px]">
          {token.slice(1, -1)}
        </code>,
      );
    } else {
      parts.push(<em key={key++}>{token.slice(1, -1)}</em>);
    }
    last = match.index + token.length;
  }

  if (last < text.length) parts.push(text.slice(last));
  return parts;
}
